default: &default
  adapter: postgresql
  encoding: utf8
  username: pgadmin
  password: devel
  host: localhost
  min_messages: 'WARNING'
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: savethekiez_development

test:
  <<: *default
  database: savethekiez_test

staging:
  <<: *default
  database: savethekiez_staging

production:
  <<: *default
  database: savethekiez_production
